[project]
name = "ytube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "playwright>=1.57.0",
    "pytube>=15.0.0",
    "requests>=2.32.5",
    "yt-dlp>=2025.12.8",
]
